{"ts": 1758032530.3222106, "event": "job_started", "data": {}}
{"ts": 1758032530.32242, "event": "info", "data": {"message": "qa_loop_start", "question": "what does google do ?"}}
{"ts": 1758032535.814311, "event": "error", "data": {"message": "qa_failed", "error": "1 validation error for Document\npage_content\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.11/v/string_type", "traceback": "Traceback (most recent call last):\n  File \"/workspaces/Pathway-Challenge/app/api/server.py\", line 108, in task\n    trace = qa.run(req.question)\n            ^^^^^^^^^^^^^^^^^^^^\n  File \"/workspaces/Pathway-Challenge/app/services/qa_loop.py\", line 90, in run\n    docs = self.store.retrieve_docs(reformulated, settings.top_k_docs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/workspaces/Pathway-Challenge/app/stores/main_store.py\", line 194, in retrieve_docs\n    return self.lc_store.retrieve_docs(query, top_k)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/workspaces/Pathway-Challenge/app/stores/langchain_store.py\", line 195, in retrieve_docs\n    docs = self._doc_retriever.get_relevant_documents(query)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/langchain_core/_api/deprecation.py\", line 193, in warning_emitting_wrapper\n    return wrapped(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/langchain_core/retrievers.py\", line 415, in get_relevant_documents\n    return self.invoke(query, config, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/langchain/retrievers/ensemble.py\", line 116, in invoke\n    result = self.rank_fusion(input, run_manager=run_manager, config=config)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/langchain/retrievers/ensemble.py\", line 226, in rank_fusion\n    retriever.invoke(\n  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/langchain_core/retrievers.py\", line 263, in invoke\n    result = self._get_relevant_documents(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/langchain_core/vectorstores/base.py\", line 1067, in _get_relevant_documents\n    docs = self.vectorstore.similarity_search(query, **kwargs_)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/langchain_community/vectorstores/qdrant.py\", line 288, in similarity_search\n    results = self.similarity_search_with_score(\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/langchain_community/vectorstores/qdrant.py\", line 364, in similarity_search_with_score\n    return self.similarity_search_with_score_by_vector(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/langchain_community/vectorstores/qdrant.py\", line 625, in similarity_search_with_score_by_vector\n    self._document_from_scored_point(\n  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/langchain_community/vectorstores/qdrant.py\", line 2004, in _document_from_scored_point\n    return Document(\n           ^^^^^^^^^\n  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/langchain_core/documents/base.py\", line 300, in __init__\n    super().__init__(page_content=page_content, **kwargs)\n  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/langchain_core/load/serializable.py\", line 115, in __init__\n    super().__init__(*args, **kwargs)\n  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/pydantic/main.py\", line 253, in __init__\n    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\npydantic_core._pydantic_core.ValidationError: 1 validation error for Document\npage_content\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.11/v/string_type\n"}}
